### PR TITLE
Mavenize project (Fixes #12)

### LINKED ISSUE #12: Maven
You should put this on a Maven repository so we can easily add it to our maven project.

### PR DESCRIPTION
**Pull request by games647**
Warning I commented out the v1_7 modules, because I didn't managed to compile it due the method conflict with 
the old

``` java
int getLastDamage()
```

and 

``` java
double getLastDamage()
```

So I maybe could ask you how do you managed i. Don't you had the same issues when you built it by manually selecting the craftbukkit jar?

### CODE REVIEW

**Comment by MarcinWieczorek** [comment]
@games647 you are everywhere I go!

**Comment by csh** [comment]
Would love this!

**Comment by MarcinWieczorek** [comment]
So would we.

**Comment by MulverineX** [comment]
Can you add the 1.11.2 and most importantly the 1.12 patches to this pull?

**Comment by MarcinWieczorek** [comment]
I don't think this will ever get merged. See #12

**Comment by MulverineX** [comment]
What I meant is can you since 1.10 1.9 etc are already added can you add 1.12 to it

**Comment by MarcinWieczorek** [comment]
What's the point? The owner won't merge this anyway.

**Comment by MulverineX** [comment]
Well, I can't figure out how to compile the 1.12 version that's mostly why lol.

**Comment by MulverineX** [comment]
Turns out he recently released a 1.12 compatible compiled jar on bukkit, it just doesn't show the correct version! Thanks for replying.

**Comment by filoghost** [comment]
It's finally here https://github.com/filoghost/HolographicDisplays/commit/dcee93e3e9ceb6a8d7a3d472a1182ab3ea05601a
Thanks @games647, this pull request was very helpful. I am open to more edits to the current Maven configuration.
In the future I will setup a Jenkins and a Maven repository.

**Pull request closed without merging**
