### PR TITLE
Add 1.16 support

### PR DESCRIPTION
**Pull request by Esophose**
Adds support for 1.16. Only includes the NMS additions required to get the plugin to function properly. 

For the 1.16 module, I'm using my own repo to get the 1.16 jar. This should be changed to use the CodeMC repo after they get the 1.16 jar added to it.

[holographicdisplays-plugin-2.4.2_1.16.zip](https://github.com/filoghost/HolographicDisplays/files/4830034/holographicdisplays-plugin-2.4.2_1.16.zip)

### CODE REVIEW

**Comment by MJRLegends** [comment]
<3 thx

**Comment by lucyy-mc** [comment]
+1 can confirm working

**Comment by HexedHero** [comment]
Works just fine for me too

**Comment by filoghost** [comment]
Thank you very much @Esophose, I merged the PR.

**Pull request merged**
