### PR TITLE
explicitly tell bukkit to cancel all tasks

### LINKED ISSUE #286: not properly shutting down async tasks
Paper 282

```
[15:30:48] [Server thread/ERROR]: Nag author: 'filoghost' of 'HolographicDisplays' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[15:30:48] [Server thread/ERROR]: Nag author: 'filoghost' of 'HolographicDisplays' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[15:30:48] [Server thread/ERROR]: Nag author: 'filoghost' of 'HolographicDisplays' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[15:30:48] [Server thread/ERROR]: Nag author: 'filoghost' of 'HolographicDisplays' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[15:30:48] [Server thread/ERROR]: Nag author: 'filoghost' of 'HolographicDisplays' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
```

### PR DESCRIPTION
**Pull request by TheRealRyGuy**
just a quick fix for error spam on disable, nothing intense here. 
fixes #286 and #507

### CODE REVIEW

**Comment by andrewkm** [comment]
Can we get this pulled in...

**Comment by andrewkm** [comment]
@filoghost

**Comment by electronicboy** [comment]
This is already done by the server after onDisable is called, not the issue here

**Comment by filoghost** [comment]
This would not work, the problem is that the async server pinger cannot be interrupted.

**Comment by andrewkm** [comment]
So like can you fix it ffs

**Pull request closed without merging**
