### PR TITLE
No need to ask bungee if there is no players online

### PR DESCRIPTION
**Pull request by KasperFranz**
There should maybe be a request when the player join to check the servers :)

### CODE REVIEW

**Comment by filoghost** [comment]
What if a player joins immediately after it has been blocked? He would see the servers offline for 3 (or whatever it's written in the config) seconds.

**Comment by KasperFranz** [comment]
That was why i said there should maybe be a check / request when a player join (and he is the only one online)

**Comment by filoghost** [comment]
The player would still see everything offline for a moment. Also, if you use the pinger, the server is probably a hub, that is usually never empty. What I'm saying, is that the minimal change is not worth the effort of disabling and enabling the pinger depending if there are players online.

**Comment by KasperFranz** [comment]
The server i'm a part of is having a empty hub most of the time (we host 2 different modpacks).

The pinger shouldnt' take more than max 100 ms to respond to the request (it takes more time to render the world etc.) so the player wouldn't see  it as offline (even for a moment)

**Comment by filoghost** [comment]
I don't feel like this is needed on most of the servers. However the pinger can take up to 2s, if the server is lagging.

**Pull request closed without merging**
