### PR TITLE
Add range checking for internal holograms

### PR DESCRIPTION
**Pull request by ykgamma**
- Added a viewRange to the database
- Players within viewRange will see the hologram
- ViewRange of 0 or less will always show hologram

### CODE REVIEW

**Comment by AerWyn81** [comment]
I am also interested in this feature :)

**Comment by SlimeDog** [comment]
[pHD](https://www.spigotmc.org/resources/77631/) supports this feature in concert with HolographicDisplays.

**Comment by filoghost** [comment]
I added a configurable view range for holograms, in config.yml (global, not per hologram): https://github.com/filoghost/HolographicDisplays/commit/39f0a0241282d587848b5518649708b23b3a3288

**Comment by SlimeDog** [comment]
Per-hologram is the desired behavior, but (as before) [pHD](https://www.spigotmc.org/resources/77631/) supports this feature.

**Comment by filoghost** [comment]
I didn't feel like that was necessary as core functionality.

**Comment by SlimeDog** [comment]
That's why [pHD](https://www.spigotmc.org/resources/77631/) was invented.

**Pull request closed without merging**
