### PR TITLE
1.20.3 & 1.20.4 support

### PR DESCRIPTION
**Pull request by rayanbzd**

### CODE REVIEW

**Comment by Tsoccerguy3** [comment]
I remember this same issue a while back with Holoplots , https://github.com/IntellectualSites/HoloPlots/issues/166 it was a issue with Holographic Displays and filoghost had fixed it

**Comment by rayanbzd** [comment]
> I remember this same issue a while back with Holoplots , [IntellectualSites/HoloPlots#166](https://github.com/IntellectualSites/HoloPlots/issues/166) it was a issue with Holographic Displays and filoghost had fixed it

Fixed. Build again and lemme know if there is any another issues.

**Comment by Tsoccerguy3** [comment]
Fixed

**Comment by Tsoccerguy3** [comment]
here is the log . Player does /plot home and the warning is triggered

[latest.log](https://github.com/filoghost/HolographicDisplays/files/13685490/latest.log)

**Comment by rayanbzd** [comment]
> here is the log . Player does /plot home and the warning is triggered
> 
> [latest.log](https://github.com/filoghost/HolographicDisplays/files/13685490/latest.log)

I don't think this come from HolographicDisplays

**Comment by Tsoccerguy3** [comment]
I isolated it to Holoplots , There is no warnings with the Holoplots plugin removed , but I don't think Holoplots will get fixed , until your PR is merged into HologramDisplay  . If you can see why the name has become null and passed onto plotsquared , please PR the fix to Holoplots. Thanks for your help .

**Comment by SoraShiunin** [comment]
Is there a guide to building the plugin or could you share a release? I'd like to update to 1.20.4 but since the plugin won't be updated anymore.

**Comment by rayanbzd** [comment]
> Is there a guide to building the plugin or could you share a release? I'd like to update to 1.20.4 but since the plugin won't be updated anymore.

https://assets.zencraft.net/plugins/HolographicDisplays-3.0.5-SNAPSHOT.jar

**Comment by andrewkm** [comment]
Thanks for this, builds fine on my end. :)

**Comment by partydragen** [comment]
> > Is there a guide to building the plugin or could you share a release? I'd like to update to 1.20.4 but since the plugin won't be updated anymore.
> 
> https://assets.zencraft.net/plugins/HolographicDisplays-3.0.5-SNAPSHOT.jar

For some reason this dies not work on my 1.20.4 server? Running latest Paper-388

**Comment by rayanbzd** [comment]
> > > Is there a guide to building the plugin or could you share a release? I'd like to update to 1.20.4 but since the plugin won't be updated anymore.
> > 
> > 
> > https://assets.zencraft.net/plugins/HolographicDisplays-3.0.5-SNAPSHOT.jar
> 
> For some reason this dies not work on my 1.20.4 server? Running latest Paper-388

Please give more details on the error

**Comment by Tsoccerguy3** [comment]
[plugins.zip](https://github.com/filoghost/HolographicDisplays/files/13940386/plugins.zip)
Here is my Holo plugin for 1.20.4 and my Holoplots to use with plotsquared

**Comment by filoghost** [comment]
Sorry everyone, I've been busier than usual last two months. In any case, I think this is one of the last official updates. I really don't have the energy of the motivation anymore to keep developing plugins.

**Comment by filoghost** [comment]
Thanks @rayanbzd for updating the plugin.

**Pull request merged**
