### PR TITLE
1.19_R1 support

### PR DESCRIPTION
**Pull request by nkomarn**
I was not initially intending to make this a PR, but I thought I might as well.

### CODE REVIEW

**Comment by meowsome** [comment]
Hi there!! Please excuse my ignorance, I'm not the best with Java. I'm trying to test this out on my server, but I'm having trouble with my setup in Intellij. I'm getting the error 

```
[HolographicDisplays] Fatal unexpected error while enabling HolographicDisplays v${pluginVersion}:
java.lang.IllegalStateException: FCommons must be relocated to another package
...
```

Could I ask for help figuring out how to relocate FCommons like it's asking?

**Comment by nkomarn** [comment]
> 

Are you building the plugin with `mvn package`? The final JAR file should be in the `plugin/target/` directory (the non-original one).

**Comment by UsainSrht** [comment]
Thanks for the pr. Built jar can be downloaded [here](https://www.mediafire.com/file/fjm0szzz5kzapk8/holographicdisplays-plugin-3.0.0-SNAPSHOT.jar/file).

**Comment by filoghost** [comment]
Thanks, unfortunately there was already another PR and I implemented it a bit differently. It's nice to see multiple contributing 😄

**Pull request closed without merging**
