### PR TITLE
Added 1.15 Support

### PR DESCRIPTION
**Pull request by Chazza**
This PR adds Spigot 1.15 support to the plugin.

Huge thanks to @GiansCode for the donation in order to help the community benefit with this new version support (e.g. for survival servers wanting to update).

### CODE REVIEW

**Comment by filoghost** [comment]
Thank you very much for this. I will merge this PR and eventually make some further minor edits.

**Comment by GiansCode** [comment]
<3

**Comment by MJRLegends** [comment]
Woo nice work

**Comment by MJRLegends** [comment]
Will there be a build out soon with this?

**Comment by filoghost** [comment]
It looks like the dependency added in the pom.xml doesn't exist yet on the repository, so the build failed. I will fix it and test the new version, as this one is probably untested.

**Comment by MJRLegends** [comment]
Sure thanks :D

**Comment by Chazza** [comment]
@filoghost it’s merely because you need to add it via build tools that’s all :)

**Comment by Chazza** [comment]
Also I’ve tested it before doing the PR, works fine for me! :)

Huge props to Gian for the donation, in order to get people to keep the open sourced project up to date.

**Comment by Chazza** [comment]
> It looks like the dependency added in the pom.xml doesn't exist yet on the repository, so the build failed. I will fix it and test the new version, as this one is probably untested.

It works fine if you run BuildTools to add it, perhaps that's always the idea (plus complies with the EULA stuff). I can also confirm the plugin runs fine and has been tested myself.

Screenshots:
- https://i.imgur.com/sxqOOHI.png
- https://i.imgur.com/eMKPUy0.png

**Comment by Chazza** [comment]
I've attached the compiled jar as well if anyone wants it until an official version has been released. This is merely the compiled version of the current source :)

I've had to zip the jar into a folder as github don't support .jar extension.
[HolographicDisplays.zip](https://github.com/filoghost/HolographicDisplays/files/3957719/HolographicDisplays.zip)

Hope it helps.

**Comment by MJRLegends** [comment]
Can confirm seems to work great @Chazza <3

**Pull request merged**
