### PR TITLE
Add API method to get Hologram from Bukkit Entity

### PR DESCRIPTION
**Pull request by Sataniel98**
Hi,
as the title says, this PR adds a method to get a Hologram from a Bukkit Entity.

Use-case: I need to exclude some plugins from PlayerInteractEntityEvent if the entity is an HD hologram spawned by my plugin.

See DRE2N/HolographicMenus/issues/15

https://github.com/DRE2N/HolographicMenus/blob/protection-fix/src/main/java/de/erethon/holographicmenus/hologram/HolographicDisplaysWrapper.java#L95

### CODE REVIEW

**Comment by filoghost** [comment]
Hello, have you seen [HologramAPI#isHologramEntity](https://github.com/filoghost/HolographicDisplays/blob/master/API/src/main/java/com/gmail/filoghost/holographicdisplays/api/HologramsAPI.java#L97-L105)?

**Comment by Sataniel98** [comment]
Is there any chance to get this merged? :C

**Comment by Sataniel98** [comment]
Could you please review this in case you're releasing an update to 1.13 soon?

**Comment by Sataniel98** [comment]
I'm sorry to bother you again @filoghost, but I can't fix my plugin without this :X Could you please have a look at it?

**Comment by Sataniel98** [comment]
Bump

**Comment by filoghost** [comment]
I'm sorry, I forgot about this issue. I wasn't able to help at the moment.

Would it be a good idea to cancel all the PlayerInteractEntityEvent at the LOWEST level (or even better, prevent the event from even being triggered)? Holograms should not be treated like normal entities.

In the worst case, I can add something similar to your PR (but making sure you can't get holograms from other plugins by default): `getHologram(Plugin plugin, Entity bukkitEntity)`

It would only check holograms from your plugin, and return null if the entity is not part of a hologram, or is part of another plugin's hologram.

**Pull request closed without merging**
